# Generated by Django 2.0.3 on 2018-03-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='imei',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
