# Generated by Django 2.0.3 on 2018-03-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_users_imei'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='nom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fuck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.fuck')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.nom')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='land.Users')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.nom')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='imei',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='pp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.pp'),
        ),
        migrations.AddField(
            model_name='mark',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.user_info'),
        ),
    ]
