# Generated by Django 2.0.3 on 2018-04-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_auto_20180328_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.nom')),
            ],
        ),
    ]
